// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	TopUpRequest
	AuthorisationRequest
	AuthoriseResponse
	Amount
	Balance
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopUpRequest struct {
	CardID string  `protobuf:"bytes,1,opt,name=cardID" json:"cardID,omitempty"`
	Amount *Amount `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *TopUpRequest) Reset()                    { *m = TopUpRequest{} }
func (m *TopUpRequest) String() string            { return proto.CompactTextString(m) }
func (*TopUpRequest) ProtoMessage()               {}
func (*TopUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TopUpRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *TopUpRequest) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

type AuthorisationRequest struct {
	CardID string  `protobuf:"bytes,1,opt,name=cardID" json:"cardID,omitempty"`
	Amount *Amount `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *AuthorisationRequest) Reset()                    { *m = AuthorisationRequest{} }
func (m *AuthorisationRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorisationRequest) ProtoMessage()               {}
func (*AuthorisationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthorisationRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *AuthorisationRequest) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

type AuthoriseResponse struct {
	Amount     *Amount `protobuf:"bytes,1,opt,name=amount" json:"amount,omitempty"`
	Authorised bool    `protobuf:"varint,2,opt,name=authorised" json:"authorised,omitempty"`
}

func (m *AuthoriseResponse) Reset()                    { *m = AuthoriseResponse{} }
func (m *AuthoriseResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthoriseResponse) ProtoMessage()               {}
func (*AuthoriseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthoriseResponse) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *AuthoriseResponse) GetAuthorised() bool {
	if m != nil {
		return m.Authorised
	}
	return false
}

type Amount struct {
	Value float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
}

func (m *Amount) Reset()                    { *m = Amount{} }
func (m *Amount) String() string            { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()               {}
func (*Amount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Amount) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Balance struct {
	Amount float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Balance) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*TopUpRequest)(nil), "prepaidcard.TopUpRequest")
	proto.RegisterType((*AuthorisationRequest)(nil), "prepaidcard.AuthorisationRequest")
	proto.RegisterType((*AuthoriseResponse)(nil), "prepaidcard.AuthoriseResponse")
	proto.RegisterType((*Amount)(nil), "prepaidcard.Amount")
	proto.RegisterType((*Balance)(nil), "prepaidcard.Balance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PrepaidCard service

type PrepaidCardClient interface {
	TopUp(ctx context.Context, in *TopUpRequest, opts ...grpc.CallOption) (*Balance, error)
	Authorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*AuthoriseResponse, error)
}

type prepaidCardClient struct {
	cc *grpc.ClientConn
}

func NewPrepaidCardClient(cc *grpc.ClientConn) PrepaidCardClient {
	return &prepaidCardClient{cc}
}

func (c *prepaidCardClient) TopUp(ctx context.Context, in *TopUpRequest, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := grpc.Invoke(ctx, "/prepaidcard.PrepaidCard/topUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prepaidCardClient) Authorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*AuthoriseResponse, error) {
	out := new(AuthoriseResponse)
	err := grpc.Invoke(ctx, "/prepaidcard.PrepaidCard/authorisation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrepaidCard service

type PrepaidCardServer interface {
	TopUp(context.Context, *TopUpRequest) (*Balance, error)
	Authorisation(context.Context, *AuthorisationRequest) (*AuthoriseResponse, error)
}

func RegisterPrepaidCardServer(s *grpc.Server, srv PrepaidCardServer) {
	s.RegisterService(&_PrepaidCard_serviceDesc, srv)
}

func _PrepaidCard_TopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrepaidCardServer).TopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prepaidcard.PrepaidCard/TopUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrepaidCardServer).TopUp(ctx, req.(*TopUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrepaidCard_Authorisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrepaidCardServer).Authorisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prepaidcard.PrepaidCard/Authorisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrepaidCardServer).Authorisation(ctx, req.(*AuthorisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrepaidCard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prepaidcard.PrepaidCard",
	HandlerType: (*PrepaidCardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "topUp",
			Handler:    _PrepaidCard_TopUp_Handler,
		},
		{
			MethodName: "authorisation",
			Handler:    _PrepaidCard_Authorisation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0xa0, 0x04, 0xb8, 0xd0, 0x01, 0x13, 0xa1, 0xd2, 0x21, 0x6a, 0x33, 0x55, 0x42,
	0xca, 0x50, 0x16, 0xd6, 0x16, 0x16, 0x36, 0x64, 0x60, 0x81, 0x85, 0x23, 0x39, 0x09, 0x4b, 0x25,
	0x36, 0xb6, 0xd3, 0x2f, 0xc3, 0x97, 0x45, 0x49, 0x1a, 0xe4, 0x48, 0x91, 0x58, 0x3a, 0xde, 0x1f,
	0xff, 0xde, 0xbd, 0x27, 0xc3, 0xc4, 0x92, 0xd9, 0xc9, 0x82, 0x72, 0x6d, 0x94, 0x53, 0x3c, 0xd6,
	0x86, 0x34, 0xca, 0xb2, 0x40, 0x53, 0x66, 0x4f, 0x70, 0xf6, 0xac, 0xf4, 0x8b, 0x16, 0xf4, 0x5d,
	0x93, 0x75, 0xfc, 0x12, 0xa2, 0xa6, 0xff, 0x70, 0x3f, 0x65, 0x73, 0xb6, 0x3c, 0x15, 0xfb, 0x8a,
	0x5f, 0x43, 0x84, 0x5f, 0xaa, 0xae, 0xdc, 0x34, 0x98, 0xb3, 0x65, 0xbc, 0xba, 0xc8, 0x3d, 0x4a,
	0xbe, 0x6e, 0x47, 0x62, 0xbf, 0x92, 0xbd, 0x41, 0xb2, 0xae, 0xdd, 0xa7, 0x32, 0xd2, 0xa2, 0x93,
	0xaa, 0x3a, 0x28, 0xfc, 0x1d, 0xce, 0x7b, 0x38, 0x09, 0xb2, 0x5a, 0x55, 0x96, 0x3c, 0x02, 0xfb,
	0x97, 0xc0, 0x53, 0x00, 0xec, 0x09, 0x65, 0x2b, 0x79, 0x22, 0xbc, 0x4e, 0x96, 0x42, 0xd4, 0xbd,
	0xe0, 0x09, 0x84, 0x3b, 0xdc, 0xd6, 0xd4, 0x52, 0x03, 0xd1, 0x15, 0xd9, 0x02, 0x8e, 0x37, 0xb8,
	0xc5, 0xaa, 0xa0, 0xc6, 0x91, 0xa7, 0x1b, 0xf4, 0x12, 0xab, 0x1f, 0x06, 0xf1, 0x63, 0x77, 0xc1,
	0x1d, 0x9a, 0x92, 0xdf, 0x42, 0xe8, 0x9a, 0x98, 0xf9, 0xd5, 0xe0, 0x30, 0x3f, 0xfa, 0x59, 0x32,
	0x18, 0xf5, 0x0a, 0x02, 0x26, 0xe8, 0x67, 0xc9, 0x17, 0x43, 0x6b, 0x23, 0x39, 0xcf, 0xd2, 0xd1,
	0x95, 0xbf, 0xb4, 0x36, 0xe1, 0xeb, 0x11, 0x6a, 0xf9, 0x11, 0xb5, 0xff, 0xe1, 0xe6, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0x2e, 0x97, 0x34, 0x20, 0x02, 0x00, 0x00,
}
