// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Amount
	Balance
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Amount struct {
	Amount   float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
	Currency string  `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"`
}

func (m *Amount) Reset()                    { *m = Amount{} }
func (m *Amount) String() string            { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()               {}
func (*Amount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Amount) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Amount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Balance struct {
	Amount   float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
	Currency string  `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Balance) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterType((*Amount)(nil), "prepaidcard.Amount")
	proto.RegisterType((*Balance)(nil), "prepaidcard.Balance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PrepaidCard service

type PrepaidCardClient interface {
	TopUp(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Balance, error)
}

type prepaidCardClient struct {
	cc *grpc.ClientConn
}

func NewPrepaidCardClient(cc *grpc.ClientConn) PrepaidCardClient {
	return &prepaidCardClient{cc}
}

func (c *prepaidCardClient) TopUp(ctx context.Context, in *Amount, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := grpc.Invoke(ctx, "/prepaidcard.PrepaidCard/topUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrepaidCard service

type PrepaidCardServer interface {
	TopUp(context.Context, *Amount) (*Balance, error)
}

func RegisterPrepaidCardServer(s *grpc.Server, srv PrepaidCardServer) {
	s.RegisterService(&_PrepaidCard_serviceDesc, srv)
}

func _PrepaidCard_TopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Amount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrepaidCardServer).TopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prepaidcard.PrepaidCard/TopUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrepaidCardServer).TopUp(ctx, req.(*Amount))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrepaidCard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prepaidcard.PrepaidCard",
	HandlerType: (*PrepaidCardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "topUp",
			Handler:    _PrepaidCard_TopUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x28, 0x4a, 0x2d, 0x48,
	0xcc, 0x4c, 0x49, 0x4e, 0x2c, 0x4a, 0x51, 0xb2, 0xe1, 0x62, 0x73, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b,
	0x11, 0x12, 0xe3, 0x62, 0x4b, 0x04, 0xb3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x82, 0xa0, 0x3c,
	0x21, 0x29, 0x2e, 0x8e, 0xe4, 0xd2, 0xa2, 0xa2, 0xd4, 0xbc, 0xe4, 0x4a, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x38, 0x5f, 0xc9, 0x96, 0x8b, 0xdd, 0x29, 0x31, 0x27, 0x31, 0x2f, 0x39, 0x95,
	0x1c, 0xed, 0x46, 0x8e, 0x5c, 0xdc, 0x01, 0x10, 0xb7, 0x38, 0x27, 0x16, 0xa5, 0x08, 0x19, 0x71,
	0xb1, 0x96, 0xe4, 0x17, 0x84, 0x16, 0x08, 0x09, 0xeb, 0x21, 0x39, 0x51, 0x0f, 0xe2, 0x3e, 0x29,
	0x11, 0x14, 0x41, 0xa8, 0xb5, 0x4e, 0xac, 0x51, 0xcc, 0x89, 0x05, 0x99, 0x49, 0x6c, 0x60, 0xaf,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0x91, 0xe5, 0x26, 0xeb, 0x00, 0x00, 0x00,
}
